package com.priorizasus.priorizasus.repository;

import static org.junit.jupiter.api.Assertions.*;

import com.priorizasus.priorizasus.entity.AuditActionType;
import com.priorizasus.priorizasus.entity.AuditLog;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

/** Validates {@link AuditLogRepository} persistence and query methods. */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class AuditLogRepositoryTest {

  @Autowired private AuditLogRepository auditLogRepository;

  @PersistenceContext private EntityManager entityManager;

  @Test
  @DisplayName("Persist and retrieve audit log by ID")
  void persistAndFindById() {
    AuditLog log =
        new AuditLog(AuditActionType.PATIENT_REGISTERED, "system", "Patient 1001 registered");
    AuditLog saved = auditLogRepository.save(log);

    assertNotNull(saved.getId());
    assertNotNull(saved.getTimestamp());
    assertNotNull(saved.getCreatedAt());

    AuditLog found = auditLogRepository.findById(saved.getId()).orElseThrow();
    assertEquals(AuditActionType.PATIENT_REGISTERED, found.getActionType());
    assertEquals("system", found.getStaffUser());
    assertEquals("Patient 1001 registered", found.getDetails());
  }

  @Test
  @DisplayName("findByActionType returns only matching entries")
  void findByActionType() {
    auditLogRepository.save(new AuditLog(AuditActionType.BOOKING, "system", "Booking 1"));
    auditLogRepository.save(new AuditLog(AuditActionType.BOOKING, "system", "Booking 2"));
    auditLogRepository.save(new AuditLog(AuditActionType.CANCELLATION, "system", "Cancel 1"));

    List<AuditLog> bookings = auditLogRepository.findByActionType(AuditActionType.BOOKING);
    assertEquals(2, bookings.size());

    List<AuditLog> cancellations =
        auditLogRepository.findByActionType(AuditActionType.CANCELLATION);
    assertEquals(1, cancellations.size());
  }

  @Test
  @DisplayName("findByPatientId returns entries for a specific Patient")
  void findByPatientId() {
    auditLogRepository.save(
        new AuditLog(AuditActionType.PATIENT_REGISTERED, "system", "P1").withPatientId(1001L));
    auditLogRepository.save(
        new AuditLog(AuditActionType.BOOKING, "system", "P1 book").withPatientId(1001L));
    auditLogRepository.save(
        new AuditLog(AuditActionType.PATIENT_REGISTERED, "system", "P2").withPatientId(1002L));

    List<AuditLog> p1Logs = auditLogRepository.findByPatientId(1001L);
    assertEquals(2, p1Logs.size());

    List<AuditLog> p2Logs = auditLogRepository.findByPatientId(1002L);
    assertEquals(1, p2Logs.size());
  }

  @Test
  @DisplayName("findByTimestampBetween filters by UTC date range")
  void findByTimestampBetween() {
    // Save logs at slightly different times
    AuditLog log1 =
        auditLogRepository.save(new AuditLog(AuditActionType.WEEKLY_SELECTION, "system", "WS 1"));
    Instant afterFirst = Instant.now();

    AuditLog log2 =
        auditLogRepository.save(new AuditLog(AuditActionType.WEEKLY_SELECTION, "system", "WS 2"));

    // Query a wide range that includes both
    Instant from = log1.getTimestamp().minus(1, ChronoUnit.HOURS);
    Instant to = log2.getTimestamp().plus(1, ChronoUnit.HOURS);

    List<AuditLog> results = auditLogRepository.findByTimestampBetween(from, to);
    assertTrue(results.size() >= 2);
  }

  @Test
  @DisplayName("findByActionTypeAndTimestampBetween combines filters")
  void findByActionTypeAndTimestampBetween() {
    Instant before = Instant.now().minus(1, ChronoUnit.HOURS);

    auditLogRepository.save(new AuditLog(AuditActionType.BOOKING, "system", "Book"));
    auditLogRepository.save(new AuditLog(AuditActionType.COMPLETED, "system", "Complete"));

    Instant after = Instant.now().plus(1, ChronoUnit.HOURS);

    List<AuditLog> bookings =
        auditLogRepository.findByActionTypeAndTimestampBetween(
            AuditActionType.BOOKING, before, after);
    assertEquals(1, bookings.size());
    assertEquals("Book", bookings.get(0).getDetails());
  }

  @Test
  @DisplayName("Timestamp is auto-generated on persist")
  void timestampAutoGenerated() {
    AuditLog log = new AuditLog(AuditActionType.STATUS_CHANGE, "system", "Status changed");
    assertNull(log.getTimestamp()); // before persist

    AuditLog saved = auditLogRepository.save(log);
    entityManager.flush();

    assertNotNull(saved.getTimestamp());
    assertNotNull(saved.getCreatedAt());
    // Timestamp and createdAt should be very close (same @PrePersist)
    long diffMillis =
        Math.abs(saved.getTimestamp().toEpochMilli() - saved.getCreatedAt().toEpochMilli());
    assertTrue(diffMillis < 1000, "timestamp and createdAt should be within 1 second");
  }
}
